### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by jiangbei01** [programmerzzx/BadBlog#1]
请问页面中应当使用什么插件或者其他组件实现博客页面的代码高亮。当前只能显示代码块，而没有代码高亮显示

**Comment by zhongzhixing** [comment]
页面中使用的是 Editor.md ，具体使用可参考其官网 http://pandao.github.io/editor.md/examples/

**Comment by zhongzx8080** [comment]
@jiangbei01  页面中使用的是 Editor.md，具体使用可参考 http://pandao.github.io/editor.md/examples/
